### ISSUE TITLE
Original data files (information) missing 

### ISSUE THREAD

**Issue by mtoseef99** [hosseinshn/AITL#1]
Dear authors @hosseinshn @ozolotareva @shumanpng, thank you very much for your new transfer learning model for input and output space adaptation. I am trying to pre-process the original data to get other data splits. For this purpose, I tried to execute `AITL_submit/data/preprocess_aitl.py`, but I couldn't find the original (pre-process) data from the following line:

https://github.com/hosseinshn/AITL/blob/f704a28578c1afcc22d5bafaa0e82207bf3985c3/AITL_submit/data/preprocess_aitl.py#L22

Could you please provide the contents of `/data/original/` for all drugs, such as:

https://github.com/hosseinshn/AITL/blob/f704a28578c1afcc22d5bafaa0e82207bf3985c3/AITL_submit/data/preprocess_aitl.py#L49

Or could you please provide the links for pre-processed files for all drugs? Thank you very much.

**Comment by hosseinshn** [comment]
Thank you for the interest in our work. The download link provided in the readme of this repository contains both utilized splits and the original data after preprocessing which you can use to get your own splits. Alternatively, you can refer to section 3.4 (Datasets) in the paper which has links to all original studies of the employed datasets.
